### ISSUE TITLE
QR code is not being loaded the second time

### ISSUE THREAD

**Issue by mmc16** [smashah/sulla#120]
**Describe the bug**
I've implemented a small server to communicate with WA. I'm using the flag `throwErrorOnTosBlock: true` and catching the error. If server's first attempt to create a headless WA client fails, it automatically clears the session data and tries again, this time headful. This second time, it doesn't get tos blocked, but it doesn't show the QR code.

**Steps to Reproduce**
1. `create(sessionName, {[params],  headless: true, throwErrorOnTosBlock: true})`
2. TOS_BLOCK
3. `.catch(.....)`
4. `fse.remove(sessionDataFolder)`
5. `create(sessionName, {[params],  headless: false, throwErrorOnTosBlock: true})`
6. Freezes on "Loading QR"
7. Gets the session timeout error

**create() code**
This is the code you use to create the client. e.g
```javascript
var sullaParams = {
            executablePath: '/usr/bin/google-chrome-stable',
            headless: true,
            throwErrorOnTosBlock: true,
            killTimer: 30,
            autoRefresh: true, //default to true
            qrRefreshS: 10,
            cacheEnabled: false
        }
sulla.create(sessionName, sullaParams)
            .then(async client => {
                .
                .
                .
            })
            .catch( async error => {
                console.log('opsy');
                sullaParams.headless = false;
                await fse.remove(sessionName);
                sulla.create(sessionName, sullaParams);
            });
```

**Expected behavior**
To show the QR Code the second time.

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
 Initializing whatsapp
Debug Info {
  WA_VERSION: 'I think you have been TOS_BLOCKed',
  PAGE_UA: 'WhatsApp/0.4.613 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36',
  SULLA_HOTFIX_VERSION: '1.7.12',
  BROWSER_VERSION: 'HeadlessChrome/79.0.3945.130'
}
Possilby TOS_BLOCKed
ℹ Authenticate to continue
✔ Loading QR
 
Seems as though you have been TOS_BLOCKed, unable to refresh QR Code. Please see https://github.com/smashah/sulla#best-practice for information on how to prevent this from happeing. You will most likely not get a QR Code
(node:2125) UnhandledPromiseRejectionWarning: Error: TOSBLOCK
    at Object.<anonymous> (/home/matheus/whatsapp_connector/source/node_modules/sulla-hotfix/dist/controllers/auth.js:99:35)
    at step (/home/matheus/whatsapp_connector/source/node_modules/sulla-hotfix/dist/controllers/auth.js:33:23)
    at Object.next (/home/matheus/whatsapp_connector/source/node_modules/sulla-hotfix/dist/controllers/auth.js:14:53)
    at fulfilled (/home/matheus/whatsapp_connector/source/node_modules/sulla-hotfix/dist/controllers/auth.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:2125) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2125) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Session timed out. Shutting down
[clears session data]
opsy
✔ Initializing whatsapp
Debug Info {
  WA_VERSION: '0.4.613',
  PAGE_UA: 'WhatsApp/0.4.613 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36',
  SULLA_HOTFIX_VERSION: '1.7.12',
  BROWSER_VERSION: 'Chrome/79.0.3945.130'
}
ℹ Authenticate to continue
✔ Loading QR
Session timed out. Shutting down

```

**Host (please complete the following information):**
 - OS: 5.3.18-1-MANJARO

**Comment by gnadelwartz** [comment]
I had also problems with tos block in the beginning, but this is gone for me

my suggestion is to first have a working create () standard configuration without tos blocking on your platform and then to code your app.

before any upgrade of sulla test if your create() configuration is working with the new version.
if not, do not upgrade.

since I following this process I had (almost) no problems with tos block ...

**Comment by mmc16** [comment]
You see, it's like, the first time I create the session (ie. no previous session data), it works fine. The problem happens when I close de server (following the best practices) and reopen it. Usually I would have to clear the session data manually, now I want to automate this though.

**Comment by e0xify** [comment]
> You see, it's like, the first time I create the session (ie. no previous session data), it works fine. The problem happens when I close de server (following the best practices) and reopen it. Usually I would have to clear the session data manually, now I want to automate this though.

same for me, first session is always fine. 
interrupting and recreating with sessions folder to get the session back, fails.

**Comment by mmc16** [comment]
> > You see, it's like, the first time I create the session (ie. no previous session data), it works fine. The problem happens when I close de server (following the best practices) and reopen it. Usually I would have to clear the session data manually, now I want to automate this though.
> 
> same for me, first session is always fine.
> interrupting and recreating with sessions folder to get the session back, fails.
> But in my case its the TOS Block

You have to at least clear the session data. Running in `headless: false` is even more guaranteed to work

**Comment by haroldorodsilva** [comment]
> > You see, it's like, the first time I create the session (ie. no previous session data), it works fine. The problem happens when I close de server (following the best practices) and reopen it. Usually I would have to clear the session data manually, now I want to automate this though.
> 
> same for me, first session is always fine.
> interrupting and recreating with sessions folder to get the session back, fails.
> But in my case its the TOS Block

Same with me. First session works fine. Restart server and tried to use the previous session that worked I get TOS_BLOCK

**Comment by smashah** [comment]
hey all, can you try running in headless false the first time, ensure you have a valid session, closing the session by closing the browser manually, then killing the node process and see if it loads up properly on subsequent tries.

**Comment by smashah** [comment]
@mmc16 @gnadelwartz @e0xify fix should be live in v1.7.23

**Comment by e0xify** [comment]
nope :( cant confirm here.
deleted session folder... started. QR code ---> quitting.
Starting again --> TOS

**Comment by smashah** [comment]
@e0xify your issue is separate to this one. Please discuss that in #110.

**Comment by e0xify** [comment]
aight sorry, will do

**Comment by smashah** [comment]
Assuming this is fixed for y'all. closing.

**Comment by mrbarnk** [comment]
This is not yet fixed. Still experiencing the same thing here.
